[WIP] New module project_status_report
camptocamp/project pull request #2
Opened 2017-09-11 13:57 UTC by jcoux

Contains (and replace): https://github.com/camptocamp/project/pull/1

2017-09-12 13:20 UTC, simahawk commented
@jcoux would you mind having a look at my review on #1?

2017-09-12 13:22 UTC, yvaucher requested changes
Some things to fix.

For the report see my comment if you want to simplify it by using attributes and a trick to have unclosed tag

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/common.py
> +INDICATOR_STATUS = [('ok', _('OK')),
No need to use _() for selection values Selection field already takes care of translations

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project.py
> +            rec.report_count = len(self.report_ids)
s/self/rec

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status.py
> +            rec.name = '%s %s' % (self.project_id.name or "", self.date)
rec to use instead of self
rec.project_id.name
rec.date

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status.py
> +    state = fields.Selection(selection=[('draft', _('Draft')),
Selection values don't need use of _()

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status.py
> +                       default=fields.Date.today(),
use the method without calling it (remove the () )

Otherwise the value of defaut will always be the date at which the server was last started

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status_indicator.py
> +        exec self.python_code in ld
Here you should use safe_eval
https://github.com/odoo/odoo/blob/10.0/odoo/tools/safe_eval.py

You can do:

``` python
safe_eval(self.python_code.strip(), ld,
          mode="exec", nocopy=True)
ld.get('color', None)
ld.get('value', None)
```

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status_indicator.py
> +            rec.display_value = '%s' % rec['value_'+rec.value_type]
here you can use

``` python
str(rec[...])
```

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status_indicator.py
> +        if self.env.user.id != SUPERUSER_ID:
self.env.uid

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status_indicator.py
> +                # TODO: check if AccessDenied or UserError ?
AccessDenied is the right one

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status_indicator.py
> +                    _('User %s tried to create a record') % self.env.user.id)
self.env.uid.

A bit more information could be useful: 'User %s (id %s) is not allowed to create an indicator value' % (self.env.user.name, self.env.uid)

Maybe explain the condition of status_report_creation. Is that a user cannot create new values on an already created report ?

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_status_indicator.py
> +                    _('User %s tried to create a record') % self.env.user.id)
s/create/write
Please see comment on the exception for create

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/models/project_task_snapshot.py
> +                    _('User %s tried to create a record') % self.env.user.id)
s/create/write

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/report/project_status_report.xml
> +                        <table width="100%">
Shouldn't the table be outside of foreach ?

2017-09-12 13:22 UTC, yvaucher commented on project_status_report/report/project_status_report.xml
> +                            </tr>
this foreach can be written that way

``` xml
<t t-foreach="o.indicator_ids" t-as="project_indicator_line">
    <t t-if="project_indicator_line_even">
        &lt;tr&gt;
    </t>
    <t t-call="project_status_report.project_status_report_project_indicator_line">
        <t t-set="project_indicator_line" t-value="project_indicator_line"/>
    </t>
    <t t-if="project_indicator_line_even">
        <t t-if="project_indicator_line_last">
            <td width=35%/>
        </t>
        <td width="10%"/>
    </t>
    <t t-if="project_indicator_odd">
        &lt;/tr&gt;
    </t>
</t>
```

foo_even : when element foo has an even index (0, 2, 4, ...)
foo_odd: when element foo has an odd index (1, 3, 5, ...)
foo_last: when element foo is the last of the list

did you try to use bootstrap.css grid here ?

2017-09-12 13:23 UTC, yvaucher commented on project_status_report/report/project_status_report.xml
> +                            </tr>
&lt;tr&gt; <- this should be supported to generate a tag which isn't closed

2017-09-12 13:27 UTC, jcoux commented
@simahawk @yvaucher For your comments about the PR https://github.com/camptocamp/project/pull/1 @CharlineDumontet will process them.
My little contribution is only the 2 last commits ;)

2017-09-13 17:36 UTC, yvaucher approved these changes

2018-02-12 10:34 UTC, CharlineDumontet approved these changes

2022-09-30 07:49 UTC, closed without merging